name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: windows-latest

    steps:
    - name: Install ruff
      uses: astral-sh/ruff-action@v3
      with:
        src: "./addon"
    - name: Check and fix
      run: ruff check --fix
    - name: Format
      run: ruff format
      