name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install ruff
      uses: astral-sh/ruff-action@v3
      with:
        src: "./addon"
    - name: Check and fix
      run: ruff check --fix
    - name: Format
      run: ruff format
    - name: Push changes
      run: |
        git checkout ${{ github.head_ref }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add .
        git commit -m "Changes from ruff"
        git push origin ${{ github.head_ref }}