name: Lint diff

on:
  [pull_request_target]

jobs:

  diff:

    runs-on: ubuntu-latest

    steps:
      - name: PR head repo
        id: head_repo_name
        run: |
          HEAD_REPO_NAME=$(jq -r '.pull_request.head.repo.full_name' "$GITHUB_EVENT_PATH")
          echo "PR head repo: $HEAD_REPO_NAME"
          echo "::set-output name=repo::$HEAD_REPO_NAME"
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: |
        git remote add upstream https://github.com/nvdaes/placeMarkers.git
        fetch upstream
        git diff -U0 upstream/master...HEAD -- addon/. > flake8.diff
        type flake8.diff | flake8 --diff --output-file=flake8.txt --tee
    - name: Comment on PR
      uses: actions/github-script@v3
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'This PR introduces flake8 errors'
          })
          