name: Lint

on:
  pull_request:

jobs:

  lint:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Lint
      run: |
        flake8 addon